# Generated by Django 3.1.2 on 2020-12-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20201228_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='date_confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
