# Generated by Django 3.1.2 on 2020-12-08 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20201208_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
