# Generated by Django 3.1.2 on 2020-12-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='date_confirmed',
            field=models.DateTimeField(blank=True),
        ),
    ]
