# Generated by Django 3.1.5 on 2021-01-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20210116_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pictures/no_profile_pic/no_image.jpg', upload_to='profile_pictures'),
        ),
    ]
