# Generated by Django 3.1.5 on 2021-01-30 22:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20210130_1048'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('mine', django.db.models.manager.Manager()),
            ],
        ),
    ]
